# Generated by Django 4.1.6 on 2023-02-09 00:21

import common.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.CharField(max_length=128)),
                ('email_to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=512), help_text='e.g. abc@email.co,xyz@gmail.com', size=None)),
                ('subject', models.CharField(max_length=128)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField()),
                ('token', models.CharField(blank=True, max_length=128)),
                ('attachment', models.FileField(blank=True, max_length=256, null=True, storage=common.utils.MediaFileSystemStorage(), upload_to='files', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
